/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vesprada
 */
import java.text.DecimalFormat;
public class PRUEBA4auto extends javax.swing.JFrame {

    /**
     * Creates new form PRUEBA4auto
     */
    public PRUEBA4auto() {
        initComponents();
        codimpresora.setVisible(false);
        lbprecioimpresora.setVisible(false);
        lbimpresoraprecio.setVisible(false);
        lbpreciopantalla.setVisible(false);
        lbpreciopantallas.setVisible(false);
        cobpantalla.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgprocesador = new javax.swing.ButtonGroup();
        bgram = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        rbi3 = new javax.swing.JRadioButton();
        rbi5 = new javax.swing.JRadioButton();
        rbi7 = new javax.swing.JRadioButton();
        jlpocesador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbddr2 = new javax.swing.JRadioButton();
        rbddr3 = new javax.swing.JRadioButton();
        rbddr4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        lbvalorinicial = new javax.swing.JLabel();
        txvalorinicial = new javax.swing.JTextField();
        cbimpresora = new javax.swing.JCheckBox();
        codimpresora = new javax.swing.JComboBox();
        cbpantalla = new javax.swing.JCheckBox();
        lbprecioram = new javax.swing.JLabel();
        lbprecioprocesador = new javax.swing.JLabel();
        cobpantalla = new javax.swing.JComboBox();
        lbprecioimpresora = new javax.swing.JLabel();
        lbpreciopantalla = new javax.swing.JLabel();
        lbratonyteclado = new javax.swing.JLabel();
        lbdescuento = new javax.swing.JLabel();
        cbtaratonyteclado = new javax.swing.JCheckBox();
        txdescuento = new javax.swing.JTextField();
        lbiva = new javax.swing.JLabel();
        txiva = new javax.swing.JTextField();
        lbtotal = new javax.swing.JLabel();
        txtotal = new javax.swing.JTextField();
        lbramprecio = new javax.swing.JLabel();
        lbimpresoraprecio = new javax.swing.JLabel();
        lbpantallaprecio = new javax.swing.JLabel();
        lbpreciopantallas = new javax.swing.JLabel();
        lbprecioratonyteclado = new javax.swing.JLabel();
        bcalcular = new javax.swing.JButton();
        lbprocesadorprecio = new javax.swing.JLabel();
        txtsiniva = new javax.swing.JTextField();
        lbsiniva = new javax.swing.JLabel();
        lb€ = new javax.swing.JLabel();
        lb€total = new javax.swing.JLabel();
        lbporcentaje = new javax.swing.JLabel();
        lbporcentajeiva = new javax.swing.JLabel();
        blimpiar = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgprocesador.add(rbi3);
        rbi3.setText("i3");
        rbi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbi3ActionPerformed(evt);
            }
        });

        bgprocesador.add(rbi5);
        rbi5.setText("i5");
        rbi5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbi5ActionPerformed(evt);
            }
        });

        bgprocesador.add(rbi7);
        rbi7.setText("i7");
        rbi7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbi7ActionPerformed(evt);
            }
        });

        jlpocesador.setText("PROCESADOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbi3)
                    .addComponent(rbi5)
                    .addComponent(rbi7))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlpocesador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jlpocesador)
                .addGap(14, 14, 14)
                .addComponent(rbi3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbi5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbi7))
        );

        jLabel1.setText("ALCOY INFORMATICA");

        bgram.add(rbddr2);
        rbddr2.setText("ddr2");
        rbddr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbddr2ActionPerformed(evt);
            }
        });

        bgram.add(rbddr3);
        rbddr3.setText("ddr3");
        rbddr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbddr3ActionPerformed(evt);
            }
        });

        bgram.add(rbddr4);
        rbddr4.setText("ddr4");
        rbddr4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbddr4ActionPerformed(evt);
            }
        });

        jLabel2.setText("RAM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbddr2)
                    .addComponent(rbddr3)
                    .addComponent(rbddr4))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(rbddr2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbddr3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbddr4))
        );

        lbvalorinicial.setText("Valor Inicial");

        txvalorinicial.setText("100");

        cbimpresora.setText("IMPRESORA");
        cbimpresora.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbimpresoraStateChanged(evt);
            }
        });
        cbimpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbimpresoraActionPerformed(evt);
            }
        });

        codimpresora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "epson", "hp", "brother" }));
        codimpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codimpresoraActionPerformed(evt);
            }
        });

        cbpantalla.setText("PANTALLA");
        cbpantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpantallaActionPerformed(evt);
            }
        });

        lbprecioram.setText("precio ram");

        lbprecioprocesador.setText("precio procesador");

        cobpantalla.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "plasma", "lcd", "led" }));
        cobpantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobpantallaActionPerformed(evt);
            }
        });

        lbprecioimpresora.setText("precio impresora");

        lbpreciopantalla.setText("precio pantalla");

        lbratonyteclado.setText("precio teclado y raton");

        lbdescuento.setText("descuento");

        cbtaratonyteclado.setText("raton y teclado");
        cbtaratonyteclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtaratonytecladoActionPerformed(evt);
            }
        });

        txdescuento.setText("0");

        lbiva.setText("iva");

        txiva.setText("0");

        lbtotal.setText("    TOTAL");

        txtotal.setEditable(false);
        txtotal.setText("0");

        lbramprecio.setText("0");

        lbimpresoraprecio.setText("0");

        lbpreciopantallas.setText("0");

        lbprecioratonyteclado.setText("0");

        bcalcular.setText("Calcular");
        bcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcalcularActionPerformed(evt);
            }
        });

        lbprocesadorprecio.setText("0");

        txtsiniva.setEditable(false);
        txtsiniva.setText("0");

        lbsiniva.setText("precio sin iva");

        lb€.setText("€");

        lb€total.setText("€");

        lbporcentaje.setText("%");

        lbporcentajeiva.setText("%");

        blimpiar.setText("Limpiar");
        blimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(161, 161, 161))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbtaratonyteclado)
                            .addComponent(bcalcular)
                            .addComponent(blimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbratonyteclado)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbdescuento)
                                    .addComponent(lbiva)
                                    .addComponent(lbtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txdescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txiva, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbsiniva)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(cobpantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbpreciopantalla))
                        .addComponent(cbpantalla)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(codimpresora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbprecioimpresora))
                        .addComponent(cbimpresora)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(93, 93, 93)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbvalorinicial, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbprecioprocesador, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbprecioram, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbporcentaje)
                            .addComponent(lbporcentajeiva)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtsiniva, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb€total, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb€)))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(lbpantallaprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbimpresoraprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbpreciopantallas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbprecioratonyteclado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbprocesadorprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txvalorinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbramprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbvalorinicial)
                            .addComponent(txvalorinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbprecioprocesador)
                            .addComponent(lbprocesadorprecio))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbprecioram)
                            .addComponent(lbramprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addComponent(cbimpresora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codimpresora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbprecioimpresora)
                            .addComponent(lbimpresoraprecio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbpantalla))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbpantallaprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cobpantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbpreciopantalla)
                    .addComponent(lbpreciopantallas))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbtaratonyteclado)
                    .addComponent(lbratonyteclado)
                    .addComponent(lbprecioratonyteclado))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsiniva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbsiniva)
                    .addComponent(lb€))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txdescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbdescuento)
                    .addComponent(lbporcentaje)
                    .addComponent(bcalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbiva)
                            .addComponent(txiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbporcentajeiva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(blimpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb€total))))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void rbi5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbi5ActionPerformed

if (rbi5 .isSelected()){
        lbprocesadorprecio.setText("60.50");

        }
    }//GEN-LAST:event_rbi5ActionPerformed

    private void rbddr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbddr3ActionPerformed
if (rbddr3 .isSelected()){
        lbramprecio.setText("30.30");

        }         // TODO add your handling code here:
    }//GEN-LAST:event_rbddr3ActionPerformed

    private void rbddr4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbddr4ActionPerformed
if (rbddr4 .isSelected()){
        lbramprecio.setText("50.90");

        }         // TODO add your handling code here:
    }//GEN-LAST:event_rbddr4ActionPerformed

    private void cbimpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbimpresoraActionPerformed


        
if (cbimpresora.isSelected()==false){

codimpresora.setVisible(false);
lbprecioimpresora.setVisible(false);
lbimpresoraprecio.setVisible(false);
lbimpresoraprecio.setText("0");
}

if (cbimpresora.isSelected()==true){

codimpresora.setVisible(true);
lbprecioimpresora.setVisible(true);
lbimpresoraprecio.setVisible(true);
codimpresora.setSelectedIndex(0);

}


// TODO add your handling code here:
    }//GEN-LAST:event_cbimpresoraActionPerformed

    private void codimpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codimpresoraActionPerformed

        
if (codimpresora.getSelectedIndex()==0){
lbimpresoraprecio.setText("50.90");
}
if (codimpresora.getSelectedIndex()==1){
lbimpresoraprecio.setText("75.95");
}
if (codimpresora.getSelectedIndex()==2){
lbimpresoraprecio.setText("40.10");
}

        
// TODO add your handling code here:
    }//GEN-LAST:event_codimpresoraActionPerformed

    private void cobpantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobpantallaActionPerformed
if (cobpantalla.getSelectedIndex()==0){
lbpreciopantallas.setText("50.60");
}
if (cobpantalla.getSelectedIndex()==1){
lbpreciopantallas.setText("75.50");
}
if (cobpantalla.getSelectedIndex()==2){
lbpreciopantallas.setText("40.40");
}       

// TODO add your handling code here:
    }//GEN-LAST:event_cobpantallaActionPerformed

    private void rbi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbi3ActionPerformed
        if (rbi3 .isSelected()){
        lbprocesadorprecio.setText("40.35");
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_rbi3ActionPerformed

    private void rbi7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbi7ActionPerformed
if (rbi7 .isSelected()){
        lbprocesadorprecio.setText("100.80");
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_rbi7ActionPerformed

    private void rbddr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbddr2ActionPerformed
if (rbddr2 .isSelected()){
        lbramprecio.setText("15.50");

        }        // TODO add your handling code here:
    }//GEN-LAST:event_rbddr2ActionPerformed

    private void cbpantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpantallaActionPerformed

        
if (cbpantalla.isSelected()==false){
cobpantalla.setVisible(false);
lbpreciopantalla.setVisible(false);
lbpreciopantallas.setVisible(false);
lbpreciopantallas.setText("0");

}
if (cbpantalla.isSelected()==true){
cobpantalla.setVisible(true);
lbpreciopantalla.setVisible(true);
lbpreciopantallas.setVisible(true);
cobpantalla.setSelectedIndex(0);
}

// TODO add your handling code here:
    }//GEN-LAST:event_cbpantallaActionPerformed

    private void cbtaratonytecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtaratonytecladoActionPerformed
if (cbtaratonyteclado.isSelected()==true){

    lbprecioratonyteclado.setText("20.65");
    
} else{
lbprecioratonyteclado.setText("0");
}
        
// TODO add your handling code here:
    }//GEN-LAST:event_cbtaratonytecladoActionPerformed

    private void bcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcalcularActionPerformed
       DecimalFormat formateador = new DecimalFormat("########.##");

       double sumasiniva= Double.parseDouble(txvalorinicial.getText())+Double.parseDouble(lbprocesadorprecio.getText())+Double.parseDouble(lbramprecio.getText())+Double.parseDouble(lbimpresoraprecio.getText())+Double.parseDouble(lbpreciopantallas.getText())+Double.parseDouble(lbprecioratonyteclado.getText());
       txtsiniva.setText(String.valueOf(sumasiniva));
       double resultadodesc=((Double.parseDouble(txtsiniva.getText()))-(Double.parseDouble(txdescuento.getText())/100)*(Double.parseDouble(txtsiniva.getText())));
       double resultado=(resultadodesc+(Double.parseDouble(txiva.getText())/100)*resultadodesc);
       String resultadodec = String.valueOf(formateador.format(resultado));
       txtotal.setText(resultadodec);
     

    }//GEN-LAST:event_bcalcularActionPerformed

    private void cbimpresoraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbimpresoraStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbimpresoraStateChanged

    private void blimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blimpiarActionPerformed
rbi3.setSelected(true);
rbddr2.setSelected(true);
if(cbimpresora.isSelected()==true){
cbimpresora.setSelected(false);
codimpresora.setVisible(false);
lbprecioimpresora.setVisible(false);
lbimpresoraprecio.setVisible(false);
lbimpresoraprecio.setText("0");
}
if(cbpantalla.isSelected()==true){
cbpantalla.setSelected(false);
cobpantalla.setVisible(false);
lbpreciopantalla.setVisible(false);
lbpreciopantallas.setVisible(false);
lbpreciopantallas.setText("0");
}
txdescuento.setText("0");
txiva.setText("0");
txtotal.setText("0");
txtsiniva.setText("0");
if (cbtaratonyteclado.isSelected()==true){
    cbtaratonyteclado.setSelected(false);
    lbprecioratonyteclado.setText("0");
}
        
// TODO add your handling code here:
    }//GEN-LAST:event_blimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRUEBA4auto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRUEBA4auto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRUEBA4auto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRUEBA4auto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRUEBA4auto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcalcular;
    private javax.swing.ButtonGroup bgprocesador;
    private javax.swing.ButtonGroup bgram;
    private javax.swing.JButton blimpiar;
    private javax.swing.JCheckBox cbimpresora;
    private javax.swing.JCheckBox cbpantalla;
    private javax.swing.JCheckBox cbtaratonyteclado;
    private javax.swing.JComboBox cobpantalla;
    private javax.swing.JComboBox codimpresora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jlpocesador;
    private javax.swing.JLabel lbdescuento;
    private javax.swing.JLabel lbimpresoraprecio;
    private javax.swing.JLabel lbiva;
    private javax.swing.JLabel lbpantallaprecio;
    private javax.swing.JLabel lbporcentaje;
    private javax.swing.JLabel lbporcentajeiva;
    private javax.swing.JLabel lbprecioimpresora;
    private javax.swing.JLabel lbpreciopantalla;
    private javax.swing.JLabel lbpreciopantallas;
    private javax.swing.JLabel lbprecioprocesador;
    private javax.swing.JLabel lbprecioram;
    private javax.swing.JLabel lbprecioratonyteclado;
    private javax.swing.JLabel lbprocesadorprecio;
    private javax.swing.JLabel lbramprecio;
    private javax.swing.JLabel lbratonyteclado;
    private javax.swing.JLabel lbsiniva;
    private javax.swing.JLabel lbtotal;
    private javax.swing.JLabel lbvalorinicial;
    private javax.swing.JLabel lb€;
    private javax.swing.JLabel lb€total;
    private javax.swing.JRadioButton rbddr2;
    private javax.swing.JRadioButton rbddr3;
    private javax.swing.JRadioButton rbddr4;
    private javax.swing.JRadioButton rbi3;
    private javax.swing.JRadioButton rbi5;
    private javax.swing.JRadioButton rbi7;
    private javax.swing.JTextField txdescuento;
    private javax.swing.JTextField txiva;
    private javax.swing.JTextField txtotal;
    private javax.swing.JTextField txtsiniva;
    private javax.swing.JTextField txvalorinicial;
    // End of variables declaration//GEN-END:variables


}
